### ISSUE TITLE
Threads error

### ISSUE THREAD

**Issue by vineeth-s** [ksahlin/isONclust#1]
When I run isONclust on ONT data with the default --t parameter, it finishes without any issues, but when I increase the number of threads from 8 to any other number I get the following error : 

`multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/vineeth/anaconda3/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/vineeth/anaconda3/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/vineeth/anaconda3/lib/python3.6/site-packages/modules/cluster.py", line 732, in reads_to_clusters_helper
    return reads_to_clusters(*args, **kwargs)
  File "/home/vineeth/anaconda3/lib/python3.6/site-packages/modules/cluster.py", line 678, in reads_to_clusters
    print("Percent passed alignment criteria out of number of calls to this module:{0}".format( round(100*aln_passed_criteria/float(aln_called), 2) ))
ZeroDivisionError: float division by zero
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/vineeth/anaconda3/bin/isONclust", line 178, in <module>
    main(args)
  File "/home/vineeth/anaconda3/bin/isONclust", line 86, in main
    clusters, cluster_seq_origin = cluster.cluster_seqs(read_array, p_emp_probs,  args)
  File "/home/vineeth/anaconda3/lib/python3.6/site-packages/modules/cluster.py", line 784, in cluster_seqs
    cluster_results =res.get(999999999) # Without the timeout this blocking call ignores all signals.
  File "/home/vineeth/anaconda3/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
ZeroDivisionError: float division by zero`

Explicitly setting --t to 8 works as well

**Comment by ksahlin** [comment]
Thanks for feedback. I will fix this bug later today as it is an easy one.
