### ISSUE TITLE
RE: IsONclust on ONY; spot died with <Signals.SIGILL: 4>.

### ISSUE THREAD

**Issue by Malabady** [ksahlin/isONclust#21]
Hi 
I am running isONclust in a Conda environment and the spoa and medaka modules are loaded before the run. 

Here is my commands:

```
ml Miniconda3/4.10.3
source activate isonclust
ml spoa/4.0.0-GCC-8.3.0
ml minimap2/2.22-GCC-8.3.0
ml medaka/1.5.0

isONclust --ont --use_old_sorted_file --fastq ./isONclust-out2/sorted.fastq  --outfolder isONclust-out2 --consensus  --t 24
```

the run failed in the consesus step when running spoa with the following kill signal. 

```
Traceback (most recent call last):
  File "/home/malabady/.conda/envs/isonclust/bin/isONclust", line 263, in <module>
    main(args)
  File "/home/malabady/.conda/envs/isonclust/bin/isONclust", line 127, in main
    center = consensus.run_spoa(reads_path.name, os.path.join(work_dir,"spoa_tmp.fa"), "spoa")
  File "/home/malabady/.conda/envs/isonclust/lib/python3.10/site-packages/modules/consensus.py", line 89, in run_spoa
    subprocess.check_call([ spoa_path, reads, "-l", "0", "-r", "0", "-g", "-2"], stdout=output_file, stderr=null)
  File "/home/malabady/.conda/envs/isonclust/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['spoa', '/tmp/tmp_12sh3ko/reads_tmp.fq', '-l', '0', '-r', '0', '-g', '-2']' died with <Signals.SIGILL: 4>.
```

I can see  ``/tmp/tmp_12sh3ko/reads_tmp.fq `` and can run spoa on the reads_tmp.fq directly. 

Any suggestions what's wrong? 

Thanks
Magdy

**Comment by ksahlin** [comment]
...and as for the actual runtime error I don't know. As you mention, if you are able to run spoa without error on the instance reported in the error message (`'spoa', '/tmp/tmp_12sh3ko/reads_tmp.fq', '-l', '0', '-r', '0', '-g', '-2'`) it is strange. 

I would have expected that this instance would be the command throwing the error.
